version: '3.7'

services:
  watermetergatewayexporter:
    image: revenberg/solarrs485exporter
    container_name: solarrs485exporter
    environment:
      - IP=192.168.2.20
      - PROMETHEUS_PORT=9008
      - LOG_LEVEL=DEBUG
    restart: always   
    ports:
      - 9008:9008
    expose:
      - 9008
